### PR TITLE
FELIX-6228: Atomos maven plugin

### PR DESCRIPTION
**Pull request by stbischof**

### CODE REVIEW

**Comment by tjwatson** [comment]
I opened JIRA https://issues.apache.org/jira/browse/FELIX-6228 to track this.

**Comment by tjwatson** [comment]
This is looking great so far.  To get the web console to work I had to patch the `additionalResourceConfig.json` file.  This is because the webconsole ends up looking for these res and templates resources using the class loader.

```
diff --git a/atomos.examples/atomos.examples.substrate.maven.equinox/additionalResourceConfig.json b/atomos.examples/atomos.examples.substrate.maven.equinox/additionalResourceConfig.json
index 9656206..f6797ac 100644
--- a/atomos.examples/atomos.examples.substrate.maven.equinox/additionalResourceConfig.json
+++ b/atomos.examples/atomos.examples.substrate.maven.equinox/additionalResourceConfig.json
@@ -2,6 +2,12 @@
        "resources": [
                {
                        "pattern": "META-INF/services/.*$"
+               },
+               {
+                       "pattern": "templates/.*$"
+               },
+               {
+                       "pattern": "res/.*$"
                }
        ]
 }
```

**Comment by stbischof** [comment]
Thank you.
But I am not sure why Graal-NI could not handle this.
https://github.com/oracle/graal/issues/1956

**Comment by tjwatson** [comment]
> Thank you.
> But I am not sure why Graal-NI could not handle this.
> [oracle/graal#1956](https://github.com/oracle/graal/issues/1956)

I'm not sure that issue is related here.  The issue isn't that we need to use a URLClassLoader to find the resources.  During native-image compilation substrate will not automatically include all available resources from the JARs on the classpath.  I *think* this is motivated by trying to keep the image as small as possible and there is no easy way for the compiler to know all the resources that are necessary for the subset of code that is getting compiled into the image.  So it is expected that you configure the resources you know are necessary.  Here we know the webconsole loads up these files from `templates/` and `res/`.  But I don't know how you know that in an automated general way.

I'm not sure how useful it is to trim out unused resources.  One option would be to just have the plugin discover all resources from the bundle JARs and put a pattern for all of them.  It will result in slightly larger images, but I doubt it will be that big as long as we limit it to the resources from the bundle JARs.

**Comment by karlpauls** [comment]
I think keeping the resources (at least by default) is a good idea.

**Pull request merged**
