### PR TITLE
remove direct dependency on Signal so that when jlink is run it doesn…

### PR DESCRIPTION
**Pull request by rotty3000**
…'t drag in jdk.unsupported just for this one call

Signed-off-by: Raymond Augé <raymond.auge@liferay.com>

### CODE REVIEW

**Comment by rotty3000** [comment]
the LGTM failure seems to be an issue I've also gotten locally. I had to disable the check `<animal.sniffer.skip>true</animal.sniffer.skip>` because it seems the error comes from the felix-parent pom outside this project.

**Comment by tjwatson** [comment]
The `jdk.unsupported` is required optionally (static) already.  Not sure why reflection is needed to make it more optional.

```
open module org.apache.felix.atomos
{
    exports org.apache.felix.atomos;

    requires transitive osgi.core;
    requires static osgi.annotation;
    requires static jdk.unsupported;
    requires static org.apache.felix.gogo.runtime;
```

**Comment by rotty3000** [comment]
yeah, this was an experiment but in the end it didn't prove much worth. thx

**Comment by tjwatson** [comment]
For what it's worth this code is here as a workaround to ensure the shutdown hooks for the jvm are run with native support.  It is possible this is no longer needed on the latest graal version. It has been a long time since I've tested with a recent version of graal.

**Pull request closed without merging**
